# Generated by Django 4.1.3 on 2022-12-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=250)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("Description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("serves", models.IntegerField()),
                ("cooktime", models.TimeField()),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes_cat",
                        to="djicook.categories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredients_Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=250)),
                ("measuretype", models.TextField()),
                ("amount", models.FloatField()),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingred",
                        to="djicook.categories",
                    ),
                ),
                (
                    "recipe",
                    models.ManyToManyField(
                        related_name="recipe_ingred", to="djicook.recipes"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cookbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.TextField()),
                (
                    "recipe",
                    models.ManyToManyField(
                        related_name="recipe_book", to="djicook.recipes"
                    ),
                ),
            ],
        ),
    ]
