# Generated by Django 4.1.3 on 2022-12-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djicook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
