# Generated by Django 4.1.3 on 2022-12-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djicook", "0003_remove_ingredients_recipes_title_recipes_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Product Image", upload_to="images"
            ),
        ),
    ]
