# Generated by Django 4.1.3 on 2022-12-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djicook", "0004_alter_recipes_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredients_recipes",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="ingredients_recipes",
            name="recipe",
        ),
        migrations.RenameField(
            model_name="recipes",
            old_name="cooktime",
            new_name="ingredients",
        ),
        migrations.RemoveField(
            model_name="categories",
            name="image",
        ),
        migrations.RemoveField(
            model_name="recipes",
            name="cat",
        ),
        migrations.RemoveField(
            model_name="recipes",
            name="serves",
        ),
        migrations.AddField(
            model_name="recipes",
            name="category",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipes",
            name="instructions",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="cookbook",
        ),
        migrations.DeleteModel(
            name="Ingredients",
        ),
        migrations.DeleteModel(
            name="Ingredients_Recipes",
        ),
    ]
