# Generated by Django 4.1.3 on 2022-12-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djicook", "0005_remove_ingredients_recipes_ingredient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipes",
            old_name="Description",
            new_name="description",
        ),
        migrations.AddField(
            model_name="categories",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
